import regex as re

def finding_a_motif_in_dna(seq_s, seq_t):
    matchiter = re.finditer(re.compile(seq_t), string=seq_s, overlapped=True)
    return [match.start() + 1 for match in matchiter]

# def finding_a_motif_in_dna_(seq_s, seq_t):
#     result = []
#     for index in len(seq_s):
#         if seq_s[index] == seq_t and seq_s[index:index+len(seq_t)] = seq_t:
#             result.append(index + 1)

if __name__ == '__main__':
    seq_s = 'TGATGGCTTATGGCTTTCTATGGCTTATGGCTTGATGGCTTTCATGGCTTGCGATGGCTTATGGCTTATGGCTTATGGCTTATGGCTTATGGCTTCGCATGGCTTATTTGATGGCTTGCAATGGCTTACATGGCTTATGGCTTGAATGGCTTCCCAGAATGGCTTTAATGGCTTTGAAGTATGGCTTCCTGCATGGCTTGCCACGAATGGCTTCCATGGCTTTATGGCTTATGGCTTGGTGATGGCTTGCTAGACATGGCTTGGATGGCTTGATGGCTTATGGCTTCATGGCTTTAACATGGCTTATGGCTTCTATGGCTTGCGACATATGGCTTTTATGGCTTCATGGCTTCCTTGATGGCTTGGTGATGGCTTAAGATGGCTTTGATGGCTTATATATGGCTTCTATGGCTTATGGCTTCGTGGTATGGCTTTGATTTATGGCTTCATGGCTTATGGCTTTCGTATGGCTTATGGCTTTTAGAAGTATGGCTTATGGCTTATGGCTTCCCTATGGCTTATGGCTTGCGGATGGCTTAATGGCTTGCATGGCTTATGGCTTTAATGGCTTTCATGGCTTATGGCTTATGGCTTCGTCATGGCTTAAAAATGGCTTGCCGCGCATGGCTTATGGCTTCAGCTATGGCTTCAATGGCTTCATGGCTTGTGGTATGGCTTCATGGCTTATGGCTTCGCCCTGGTATGGCTTATGGCTTCACCATGGCTTATGGCTTCCTTACTGCGGATGGCTTGGATGGCTTACACAATGGCTTAGTATGGCTTCTCAATGGCTTAGGTTAAGGTGGTTATGGCTTGAGGCAATGGCTTATGGCTTCATGGCTTAGATGGCTTTACTCCATGGCTTGTATGGCTTTATGGCTTATCATGGCTTATGGCTTATGGCTTATGGCTTAATGGCTTAATGGCTTAATGGCTTGCGATGGCTTACGTTAATGGCTTTGAATGGCTTTCAGATGGCTT'
    seq_t = 'ATGGCTTAT'
    result = finding_a_motif_in_dna(seq_s, seq_t)
    print(result)